### ISSUE TITLE
Problem in sub-dependency prevents bundling projects relying on square-nodejs-sdk

### ISSUE THREAD

**Issue by tia-gbenson** [square/square-nodejs-sdk#46]
This problem expresses itself in the form of the following runtime error on projects that have been bundled with webpack (as is often useful for reducing package sizes when running a square-dependent project inside an AWS Lambda function):
```
TypeError: Right-hand side of 'instanceof' is not callable
    at str (***:/node_modules/json-bigint/lib/stringify.js:218:1)
    at Function.module.exports.JSON.stringify (***:/node_modules/json-bigint/lib/stringify.js:380:1)
(...rest of stack trace here...)
```

The cause for this is [this bug](https://github.com/sidorares/json-bigint/issues/34) in `json-bigint`, which has been open for over a year.  In turn, the root cause of `json-bigint`'s woes is the same root cause as [this two-year-old bug](https://github.com/MikeMcl/bignumber.js/issues/217), which `bignumber.js` has indicated an unwillingness to correct.

A workaround is [described here](https://github.com/sidorares/json-bigint/issues/34#issuecomment-823368370), but this often requires that npm's `unsafe-perm` option be turned on, which is clearly sub-optimal.

If I thought there was any chance that either `json-bigint` or `bignumber.js` would correct this, I wouldn't bring it up in this forum.  However, since this problem has a very real impact on usage of this library, my hope is that it can be addressed here.

**Comment by onxb** [comment]
Very well written. 
For what it's worth, I am experiencing the exact same difficulty.

**Comment by diego1686** [comment]
I'm facing the same error. Any workaround about this?
