### ISSUE TITLE
Cannot find module 'square'

### ISSUE THREAD

**Issue by hetkpatel** [square/square-nodejs-sdk#6]
I've installed the package through npm with `npm i square` but when I try to run it this is what I get:

```
Error: Cannot find module 'square'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/functions/index.js:13:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by StephenJosey** [comment]
Did you receive any errors when running `npm install square`?

**Comment by hetkpatel** [comment]
Nope, and I also see the square package folder under the `node_modules` folder.

**Comment by HectorGit** [comment]
Having the same problem

**Comment by sseaman** [comment]
Please try now.  We found an issue in our npm package and it should work for version 8.0.1

**Comment by hetkpatel** [comment]
Works now, thank you!
