### ISSUE TITLE
Issue with coordinates

### ISSUE THREAD

**Issue by AvramCatalin** [square/square-nodejs-sdk#63]
Any square library version after 8.1.1 has the following problem with the locations API:

`Cannot convert 46.77088723336634 to a BigInt
    at DefaultRequestBuilder.<anonymous> (/node_modules/@apimatic/core/lib/http/requestBuilder.js:298:35)
    at step (/node_modules/@apimatic/core/node_modules/tslib/tslib.js:143:27)
    at Object.next (/node_modules/@apimatic/core/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/node_modules/@apimatic/core/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

I am using node v14 in my project.

**Comment by techgyani** [comment]
May be below observation will help to solve this issue:

This SDK is trying to convert floating point coordinates received in the response to bigint.

Floating point number is not an integer and thus cannot be converted to big int. #24 workaround does not help to fix this issue because we are parsing the JSON response here instead of stringifying it. See https://jsfiddle.net/oku57jdt/

   "coordinates": {
    "latitude": 38.8388731541254,
    "longitude": zzzzz
   },


> Cannot convert 38.8388731541254 to a BigInt
    at DefaultRequestBuilder.<anonymous> (/Users/bhupen/projects/bk-square-service/node_modules/@apimatic/core/lib/http/requestBuilder.js:301:35)
    at step (/Users/bhupen/projects/bk-square-service/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/bhupen/projects/bk-square-service/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/bhupen/projects/bk-square-service/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by wolfadex** [comment]
@techgyani thank you pointing this out. I completely missed the fact that it's trying to convert a fractional number to a `BigInt`, which will always fail no matter the length.

**Comment by wolfadex** [comment]
This issue has been fixed with the release of 17.30.
