### ISSUE TITLE
Cannot set property '_config' of undefined

### ISSUE THREAD

**Issue by hetkpatel** [square/square-nodejs-sdk#7]
Issue running

```
const { Client, Environment } = require('square');

const client = Client({
    environment: Environment.Sandbox,
    accessToken: ACCESS_TOKEN
});
```

Error log:
```
TypeError: Cannot set property '_config' of undefined
    at Client (/functions/node_modules/square/dist/square.cjs.development.js:19785:18)
    at Object.<anonymous> (/functions/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by hetkpatel** [comment]
Solved the issue.
